kind: Service
apiVersion: v1
metadata:
  name: april-prt-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: prt
  ports:
    - name: http-port
      targetPort: 80
      port: 80
      nodePort: 30010
